version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
    wrapcheck:
      extra-ignore-sigs:
        - .Unrecoverable(
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  disable:
    - wsl
    - exhaustruct
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  fix: true
output:
  formats:
    tab:
      path: ./lint.txt
      colors: false
  sort-order:
    - linter
    - severity
    - file
severity:
  default: "@linter"
  rules:
    - linters:
        - gochecknoglobals
      severity: info
